language: cpp
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CC_=gcc-5
        - CXX_=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-5
      env:
        - CC_=clang-5.0
        - CXX_=clang++-5.0

before_install:
  - export CC=$CC_
  - export CXX=$CXX_

install:
  - make install_eigen

script:
  - mkdir -p build
  - cd build
  - cmake -D Eigen3_INCLUDE_DIR="../eigen3/" -D RSVD_OPENMP=OFF ..
  - make all
  - ./rsvd_test
